### ISSUE TITLE
Remaining file naming issues

### ISSUE THREAD

**Issue by sschuberth** [spdx/license-list-data#4] opened 2016-04-22 19:06 UTC
@goneall I believe there are some more issues:

- I think it's weird how the files in the `template` directory are named. Why is `html` part of the extension? I'd suggest to instead of e.g. `0BSD.html-template.txt` name the files like `0BSD.template.txt`.
- Similarly, in the `text` directory instead of e.g. `0BSD.html.txt` the files should be named `0BSD.txt`.
- In the `website` directory the files without an extension seem to be equivalent to the files with the same base name and an `.html` extension. So why keep both? Also e.g. `website/0BSD.json` seems to be equivalent to `json/details/0BSD.json`. Again, so why keep both?

**Comment by goneall** [comment] 2016-04-24 18:08
@sschuberth Agree on bullets 1 and 2 above - renamed the files per your suggestion.  

On the 3rd bullet, the website directory contain the generated files for the http://spdx.org/licenses website.  I'm not sure if there is much value in duplicating the website files in the git repo, but since the license file generator tool produces these files I though I would include them in the repo (it is easier to keep them than to delete them).  This is why there is a duplicate of the website .json files - the website store the json files in a flat directory structure and makes them web accessible for those wanting to access JSON formats without using git.  

In terms of the duplicated .html and no extension - this is for compatibility with previous website versions.  Originally, the HTML files did not contain the .html extensions.  The HTML files contain RDFa information which is accessed programmaticly by some tools.  There were several website configuration and HTML rendering issues caused by there being no HTML extension.  After some significant effort to fix, we decided to just add the .html extensions and keep the original duplicate files for compatibility reasons.  The .html extensions are the preferred files to access programmaticly and the .html files are used in rendering the web pages for browser access to the license list.

**Closed by goneall** 2016-04-24 18:08 UTC

**Comment by sschuberth** [comment] 2016-04-24 19:22
@goneall Thanks for the fixes and explanation.
